apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: ttl.sh/postgres-backup:1h 
            command:
            - /usr/local/bin/backup.sh 
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: DB_NAME
              value: postgres
            - name: DB_HOST
              value: postgres.default.svc.cluster.local
            - name: BACKUP_DIR
              value: /mnt/backups
            volumeMounts:
            - name: postgres-backup
              mountPath: /mnt/backups
          restartPolicy: OnFailure
          volumes:
          - name: postgres-backup
            persistentVolumeClaim:
              claimName: db-backup-pv-claim

